version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 8080:80

  frontend:
    build: ./frontend
    links: 
      - backend
    ports:
      - 8081:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf