version: '3'

services:
  demo-backend:
    build: ./backend
    image: jakst/demo-backend:1
    ports:
      - 8080:80

  demo-frontend:
    build: ./frontend
    image: jakst/demo-frontend:3
    links: 
      - demo-backend
    ports:
      - 8082:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf