apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.externalPort }}
    targetPort: {{ .Values.backend.internalPort }}
  selector:
    app: {{ .Values.backend.name }}-app
